# Generated by Django 6.0.3 on 2026-03-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq_model',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('sport', 'Sport'), ('life', 'Life'), ('video', 'Video'), ('site', 'Site'), ('games', 'Games'), ('interestings', 'Interestings'), ('fellings', 'Fellings'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
