# Generated by Django 6.0.3 on 2026-04-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_model_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq_model',
            name='answer',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
