# Generated by Django 6.0.3 on 2026-04-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='student',
            new_name='user_profile',
        ),
    ]
