# Generated by Django 4.2.29 on 2026-04-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file_type',
            field=models.CharField(choices=[('video', 'Відео'), ('file', 'Файл'), ('img', 'Картинка')], default='video', max_length=100),
        ),
    ]
