# Generated by Django 4.2.27 on 2026-04-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='material_img',
        ),
        migrations.AddField(
            model_name='material_imgcustom',
            name='image',
            field=models.ImageField(default='', upload_to='materials_media/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material_imgcustom',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='materials.material'),
            preserve_default=False,
        ),
    ]
