# Generated by Django 4.2.29 on 2026-04-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_remove_material_material_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='subtitle',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
