# Generated by Django 4.2.29 on 2026-04-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_material_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file_type',
            field=models.CharField(choices=[('video', 'Відео'), ('file', 'Файл')], default='video', max_length=100),
        ),
    ]
